name: music_app_boom
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  bloc: ^8.1.4
  build_runner: ^2.4.11
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  # Authentication
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0

  # Cloud Storage
  firebase_storage: ^12.1.1
  
  # audio
  audioplayers: ^6.0.0
  audio_video_progress_bar: ^2.0.3
  just_audio: ^0.9.39
  flutter_bloc: ^8.1.6
  rxdart: ^0.28.0
  logging: ^1.2.0
  dartz: ^0.10.1

  # favourite
  get: ^4.6.6
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6
  
  flutter:
    sdk: flutter
  freezed: ^2.4.4
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  provider: ^6.1.2
  
  

  
  
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - picture/mandopop/Gulf of Alaska.png
    - picture/mandopop/long.png
    - picture/mandopop/a friend like you.png
    - picture/mandopop/best friend.png
    - picture/mandopop/I'm too stupid.png
    - picture/kpop/boombayah.png
    - picture/kpop/easy.png
    - picture/kpop/bubble gum.png
    - picture/kpop/smart.png
    - picture/kpop/magnetic.png

    # font:

  uses-material-design: true
