name: music_app_boom
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  animations: ^2.0.11
  bloc: ^8.1.4
  build_runner: ^2.4.11
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.6
  # Authentication
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  # Cloud Storage
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  freezed: ^2.4.4
  freezed_annotation: ^2.4.4
  http: ^1.2.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - picture/Gulf of Alaska.png
    - picture/long.png
    - picture/a friend like you.png
    - picture/best friend.png
    - picture/I'm too stupid.png
    - picture/boombayah.png
    - picture/easy.png
    - picture/bubble gum.png
    - picture/smart.png
    - picture/magnetic.png
    - picture/logo.png

  uses-material-design: true
